version: '3'
services:
  python_server:
    image: python_server
    network_mode: "host"
    container_name: python_server_con
    privileged: true
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    
